service: gybd

plugins:
- serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:APP_STAGE}
  region: ${env:AWS_REGION}
  apiKeys:
  - gybd-${self:provider.stage}-api-key
  usagePlan:
    quota:
      limit: 1000
      offset: 0
      period: DAY
    throttle:
      burstLimit: 100
      rateLimit: 1

package:
  exclude:
  - ./**
  include:
  - build/**

functions:
  helloWorld:
    handler: build/handler.helloWorld
    events:
    - http:
        path: hello-world
        method: get
        cors: true
        private: true
