export const SET_CURRENT_PLAN_ID = 'SET_CURRENT_PLAN_ID';
export type SET_CURRENT_PLAN_ID = typeof SET_CURRENT_PLAN_ID;

export const SET_TASK_TITLE = 'SET_TASK_TITLE';
export type SET_TASK_TITLE = typeof SET_TASK_TITLE;

export const SET_TASK_ASSIGNEE = 'SET_TASK_ASSIGNEE';
export type SET_TASK_ASSIGNEE = typeof SET_TASK_ASSIGNEE;

export const SET_TASK_LOCATION = 'SET_TASK_LOCATION';
export type SET_TASK_LOCATION = typeof SET_TASK_LOCATION;

export const SET_TASK_DONE = 'SET_TASK_DONE';
export type SET_TASK_DONE = typeof SET_TASK_DONE;

export const ADD_PREREQUISITE_TASK = 'ADD_PREREQUISITE_TASK';
export type ADD_PREREQUISITE_TASK = typeof ADD_PREREQUISITE_TASK;

export const REMOVE_PREREQUISITE_TASK = 'REMOVE_PREREQUISITE_TASK';
export type REMOVE_PREREQUISITE_TASK = typeof REMOVE_PREREQUISITE_TASK;
