export const SET_CURRENT_PLAN_ID = 'SET_CURRENT_PLAN_ID';
export type SET_CURRENT_PLAN_ID = typeof SET_CURRENT_PLAN_ID;

export const SET_TASK_TITLE = 'SET_TASK_TITLE';
export type SET_TASK_TITLE = typeof SET_TASK_TITLE;

export const SET_TASK_ASSIGNEE = 'SET_TASK_ASSIGNEE';
export type SET_TASK_ASSIGNEE = typeof SET_TASK_ASSIGNEE;
