service: gybd

plugins:
- serverless-offline

custom:
  stackName: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs6.10
  # Default stage and region are sourced from environment variables, so must be explicit.
  # --stage and --region will still override these if supplied.
  stage: ${env:APP_STAGE}
  region: ${env:AWS_REGION}
  # Resource names are supplied to Lambda by environment variables.
  # Create them all here and use them in resource definitions.
  environment:
    GYBD_TABLE_STATES: ${self:custom.stackName}-states
  apiKeys:
  - ${self:custom.stackName}-api-key
  usagePlan:
    quota:
      limit: 1000
      offset: 0
      period: DAY
    throttle:
      burstLimit: 100
      rateLimit: 1
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:GetItem
    Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.stackName}-*"
package:
  exclude:
  - ./**
  include:
  - build/**

functions:
  authorize:
    handler: build/authorize.authorize
  getState:
    handler: build/getState.getState
    events:
    - http:
        path: states/{stateID}
        method: get
        cors: true
        private: true
        authorizer: authorize

resources:
  Resources:
    StatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.GYBD_TABLE_STATES}
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
